# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User.create(name: "Anthony", email: "anthony@nomads.com", password: "1234")
# User.create(name: "Jee", email: "jee@nomads.com", password: "1234")
# User.create(name: "Angelina", email: "angelina@nomads.com", password: "1234")
# User.create(name: "Eric", email: "eric@nomads.com", password: "1234")
# User.create(name: "Malorie", email: "malorie@nomads.com", password: "1234")
# User.create(name: "Jath", email: "jath@nomads.com", password: "1234")
# User.create(name: "Pablo", email: "pablo@nomads.com", password: "1234")
# User.create(name: "Steven", email: "steven@nomads.com", password: "1234")
# Neighborhood.create(name: "Dumbo")
# Neighborhood.create(name: "Brooklyn Heights")
# Neighborhood.create(name: "Park Slope")
# Neighborhood.create(name: "Chinatown")
# Neighborhood.create(name: "Midtown")
# Neighborhood.create(name: "Harlem")
# Neighborhood.create(name: "Bensonhurst")
# Neighborhood.create(name: "Fresh Meadows")
# Neighborhood.create(name: "East Village")
# Neighborhood.create(name: "Hell's Kitchen")
Truck.create(name: "Halal Cart Dumbo", specialty: "Halal Food", neighborhood_id: 31)
Truck.create(name: "Ming's Wok", specialty: "Chinese Food", neighborhood_id: 31)
Truck.create(name: "Kimchi Winchi", specialty: "Korean Food", neighborhood_id: 31)
Truck.create(name: "Big Burg", specialty: "American Food", neighborhood_id: 31)
Truck.create(name: "Rice King", specialty: "Chinese Food", neighborhood_id: 31)
Truck.create(name: "Curry Heights", specialty: "Indian Food", neighborhood_id: 31)
Truck.create(name: "Julian's Pizza", specialty: "Italian Food", neighborhood_id: 32)
Truck.create(name: "Bon Zon", specialty: "Korean Food", neighborhood_id: 32)
Truck.create(name: "Chiphotel", specialty: "Mexican Food", neighborhood_id: 32)
Truck.create(name: "Creamy's", specialty: "Dessert ", neighborhood_id: 32)
Truck.create(name: "Sushi Heaven", specialty: "Japanese Food", neighborhood_id: 32)
Truck.create(name: "Rumbling Dumplings", specialty: "Chinese Food", neighborhood_id: 34)
Truck.create(name: "Dim Sum Hum", specialty: "Chinese Food", neighborhood_id: 34)
Truck.create(name: "Joe Shmoe Shanghai", specialty: "Chinese Food", neighborhood_id: 34)
Truck.create(name: "El Diablo Tacos", specialty: "Mexican Food", neighborhood_id: 35)
Truck.create(name: "Eddie's Pizaa", specialty: "Italian Food", neighborhood_id: 35)
Truck.create(name: "Gorilla Cheese", specialty: "Korean Food", neighborhood_id: 35)
Truck.create(name: "Side Walk Tacos", specialty: "Mexican Food", neighborhood_id: 36)
Truck.create(name: "Falafel Hub", specialty: "Mediterranean Food", neighborhood_id: 37)
Truck.create(name: "Veggies On Ice", specialty: "Vegetarian Food", neighborhood_id: 37)
Truck.create(name: "Sally's Cupcakes", specialty: "Dessert", neighborhood_id: 38)
Truck.create(name: "Crappy Crabs", specialty: "Seafood", neighborhood_id: 39)
Truck.create(name: "Wing a Ding", specialty: "American Food", neighborhood_id: 40)
